// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY753AhYaacmgYCrg456ZYmrx4r0-gjTU',
    appId: '1:554362535300:android:0f09f6cb574b2820ab31d1',
    messagingSenderId: '554362535300',
    projectId: 'veritag-5b2cf',
    storageBucket: 'veritag-5b2cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUu6qXZ95LBQNBZOGELcFJ_9b4Vuod9s4',
    appId: '1:554362535300:ios:d39cd19873cb19bdab31d1',
    messagingSenderId: '554362535300',
    projectId: 'veritag-5b2cf',
    storageBucket: 'veritag-5b2cf.appspot.com',
    iosBundleId: 'com.example.veritagApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD9snSy0IPDU6LArIEWDMl-OPsWUEpMPA',
    appId: '1:554362535300:web:913d04c9bb61f4faab31d1',
    messagingSenderId: '554362535300',
    projectId: 'veritag-5b2cf',
    authDomain: 'veritag-5b2cf.firebaseapp.com',
    storageBucket: 'veritag-5b2cf.appspot.com',
    measurementId: 'G-LMMQW1D3WT',
  );

}