/// Flutter icons Ohome
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Ohome
///      fonts:
///       - asset: fonts/Ohome.ttf
///
/// 
///
library;
import 'package:flutter/widgets.dart';

class Ohome {
  Ohome._();

  static const _kFontFam = 'Ohome';
  static const String? _kFontPkg = null;

  static const IconData oc_home = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
